Fix missing-prototypes
mailwatch-common.c:30:1: error: no previous prototype for 'xfce_mailwatch_get_error_quark' [-Werror=missing-prototypes]
mailwatch-common.c:41:1: error: no previous prototype for 'xfce_mailwatch_threads_enter' [-Werror=missing-prototypes]
mailwatch-common.c:46:6: error: no previous prototype for 'xfce_mailwatch_threads_leave' [-Werror=missing-prototypes]
mailwatch.c:113:1: error: no previous prototype for 'xfce_mailwatch_new' [-Werror=missing-prototypes]
mailwatch-net-conn.c:283:1: error: no previous prototype for 'xfce_mailwatch_net_conn_init' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>